### ISSUE TITLE
silent=True does not silence

### ISSUE THREAD

**Issue by codykingham** [annotation/text-fabric#47] opened 2019-05-14 13:52 UTC
BHSA app load with silent = True now produces a read out. Before latest update it was quiet.

**Comment by codykingham** [comment] 2019-05-14 13:53
<img width="903" alt="Screen Shot 2019-05-14 at 14 52 59" src="https://user-images.githubusercontent.com/17049294/57703435-f8ce1b00-7657-11e9-973a-d989a0013f47.png">

**Comment by dirkroorda** [comment] 2019-05-14 14:47
I found the cause, remedied it, will be in the next release!

**Comment by codykingham** [comment] 2019-05-16 14:26
Sorry to bring this up again, as it is so minor. But i've found that the core TF api also does not silence when loading new data (the C__ reports). Also, the warning about missing dependencies when loading from a blank directory (for saving) is not silenced.
<img width="577" alt="Screen Shot 2019-05-16 at 15 25 41" src="https://user-images.githubusercontent.com/17049294/57861692-f8b45380-77ee-11e9-9c9d-e5865bc35cfb.png">

**Comment by dirkroorda** [comment] 2019-06-29 07:07
Fixed

**Closed by dirkroorda** 2019-06-29 07:07 UTC
Labels: bug
